### ISSUE TITLE
Where to download the  'icp' dataset which  should be put into 'data/kitti/icp' ?

### ISSUE THREAD

**Issue by Violetit** [XuyangBai/D3Feat#24]
Hi @XuyangBai 

Does the `data/kitti/icp` can be download from the web page [KITTI Odometry website.](http://www.cvlibs.net/datasets/kitti/eval_odometry.php)? Cound you tell me which `.zip` is the `icp` data, and I should download?
By the way, I have changed the CUDA version to 9.2 and tensorflow-gpu=1.12.3, it seems goes well now.

Waiting for your reply! 
Best regards!

**Comment by Violetit** [comment]
Hi @XuyangBai 
I try to gegerated the `icp` from FCGF project. Something went wrong:
```
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main(config)
  File "train.py", line 63, in main
    trainer.train()
  File "/disk/tia/FCGF/lib/trainer.py", line 124, in train
    val_dict = self._valid_epoch()
  File "/disk/tia/FCGF/lib/trainer.py", line 314, in _valid_epoch
    input_dict = data_loader_iter.next()
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/disk/tia/FCGF/lib/data_loaders.py", line 71, in collate_pair_fn
    coords_batch0, feats_batch0 = ME.utils.sparse_collate(coords0, feats0)   #  这里有错，feats里面什么都没有。 AssertionError: Coordinate length 135925 != Feature length 0
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/site-packages/MinkowskiEngine/utils/collation.py", line 124, in sparse_collate
    assert N == Nf, f"Coordinate length {N} != Feature length {Nf}"
AssertionError: Coordinate length 10927 != Feature length 2

Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/.conda/envs/py3-fcgf/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/disk/tia/FCGF/scripts/test_kitti.py", line 144, in <module>
    main(config)
  File "/disk/tia/FCGF/scripts/test_kitti.py", line 27, in main
    config, config.test_phase, 1, num_threads=config.test_num_workers, shuffle=True)
AttributeError: 'EasyDict' object has no attribute 'test_num_workers'
``` 
And I don't know how to solve this bug. Could you have some idea about it? Or could you please share the `icp` dataset with me? 
By the way, I tried to train the 3dmatch on FCGF before, but during the testing step, some similar data dimensions mismatch errors were reported. I opened an issue, and no one has responded to that until now.

Waiting for your reply!
Best regards!

#https://github.com/chrischoy/FCGF/issues/39
#https://github.com/chrischoy/FCGF/issues/38

**Comment by XuyangBai** [comment]
I borrow the KITTI dataset class from FCGF repo, so basically they are the same. The `icp` folder is generated when you run the training code of KITTI for the first time. You may read the code [here](https://github.com/XuyangBai/D3Feat/blob/9ca3f011dab41f51885c0836d7dd77ecf041bd37/datasets/KITTI.py#L51), it is easy to figure out which zip file should be downloaded from the KITTI website (laser data, poses). Good luck.

Best,
Xuyang

**Comment by Violetit** [comment]
> I borrow the KITTI dataset class from FCGF repo, so basically they are the same. The `icp` folder is generated when you run the training code of KITTI for the first time. You may read the code [here](https://github.com/XuyangBai/D3Feat/blob/9ca3f011dab41f51885c0836d7dd77ecf041bd37/datasets/KITTI.py#L51), it is easy to figure out which zip file should be downloaded from the KITTI website (laser data, poses). Good luck.
> 
> Best,
> Xuyang

Thank you very much, the program has run correctly.
